title: Project St33l
description: Feast your eyes on my works.
baseurl:
url: https://st33lrain.github.io
theme: minima

navigation:
  -title: Home
  url: /
  -title: Projects
  sublinks:
    -title: Kali Thumbdrive
    url: /Project/Kali-Thumbdrive.html
    -title: Penetration Testing Lab
    url: /Project/Penetration-Testing-Lab.html
    -title: Docs
    url: /projects/docs.html
  -title: About
  url: /about.html
